# Generated by Django 3.1.5 on 2021-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
