# Generated by Django 3.1.5 on 2021-01-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_user_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_manager',
            name='city',
        ),
    ]
